CREATE ROLE dbowner WITH
  NOLOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT USAGE, CREATE ON SCHEMA public TO dbowner;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dbowner;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dbowner;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO dbowner;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO dbowner;
GRANT CONNECT ON DATABASE Survey TO dbowner;
GRANT CREATE ON DATABASE Survey to dbowner;

CREATE ROLE dbuser WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT USAGE ON SCHEMA public TO dbuser;
GRANT CONNECT ON DATABASE Survey TO dbuser;
GRANT USAGE ON SCHEMA public TO dbuser;

CREATE ROLE survey_owner WITH
    LOGIN
    SUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD 'SURVEYPW';

GRANT dbowner to survey_owner;

CREATE ROLE survey_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SURVEYPW';

-- I need to research this. I don't know if I want to give this much power to user.
-- In order to allow it to create tables. Maybe this function of the ETL Service belongs in the admin tool. 
-- GRANT dbuser TO survey_user; 
GRANT dbowner TO survey_user;

CREATE ROLE surveyadmin_owner WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SAOWNERPW';

GRANT dbowner to surveyadmin_owner;

CREATE ROLE surveyadmin_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SAOWNERPW';

GRANT dbuser TO surveyadmin_user;

CREATE ROLE surveyreport_owner WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SROWNERPW';

GRANT dbowner to surveyreport_owner;

CREATE ROLE surveyreport_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SRUSERPW';

GRANT dbuser TO surveyreport_user;