-- Relatives: one row per reported relative (respondent_id, step, step_instance). Tabs = first 10 columns.
select step                                    as "Relative",
       max(nullif(gender,''))                  as "Gender",
       max(nullif(vital_status,''))            as "Vital status",
       max(nullif(generation,''))::numeric     as "Generation",
       max(nullif(relationship,''))::numeric   as "Relationship",
       max(nullif(race,''))                    as "Race",
       max(nullif(ashkenazi,''))               as "Ashkenazi",
       max(nullif(latinx,''))                  as "LatinX",
       max(nullif(age,''))::numeric            as "Age",
       case when 'true' in (
           max(bladder_cancer),
           max(breast_cancer),
           max(colon_or_rectal_cancer),
           max(endometrial_or_uterine_cancer),
           max(kidney_renal_cell_cancer),
           max(leukemia),
           max(lung_cancer),
           max(lymphoma),
           max(melanoma_skin_cancer),
           max(nonmelanoma_skin_cancer),
           max(oral_cavity_or_throat_cancer),
           max(other_cancer),
           max(ovarian_cancer),
           max(pancreatic_cancer),
           max(prostate_cancer),
           max(stomach_cancer),
           max(testicular_cancer),
           max(thyroid_cancer),
           max(unknown_cancer)
       ) then 'yes' else 'no' end             as "Any cancer",
       max(nullif(sibling_type,''))            as "Sibling type",
       max(nullif(shared_parent,''))           as "Shared parent",
       max(nullif(triple_negative_breast_cancer,'')) as "Triple negative",
       max(nullif(other_cancer_name,''))       as "Other cancer name",
       max(nullif(bladder_cancer,'')) as "Bladder Cancer",
       max(nullif(bladder_cancer_age,''))::numeric as "Bladder Cancer Age",
       max(nullif(multiple_bladder_cancers,'')) as "Multiple Bladder Cancer",
       max(nullif(breast_cancer,'')) as "Breast Cancer",
       max(nullif(breast_cancer_age,''))::numeric as "Breast Cancer Age",
       max(nullif(multiple_breast_cancers,'')) as "Multiple Breast Cancer",
       max(nullif(colon_or_rectal_cancer,'')) as "Colon or Rectal Cancer",
       max(nullif(colon_or_rectal_cancer_age,''))::numeric as "Colon or Rectal Cancer Age",
       max(nullif(multiple_colon_or_rectal_cancers,'')) as "Multiple Colon or Rectal Cancer",
       max(nullif(endometrial_or_uterine_cancer,'')) as "Endometrial or Uterine Cancer",
       max(nullif(endometrial_or_uterine_cancer_age,''))::numeric as "Endometrial or Uterine Cancer Age",
       max(nullif(multiple_endometrial_or_uterine_cancers,'')) as "Multiple Endometrial or Uterine Cancer",
       max(nullif(kidney_renal_cell_cancer,'')) as "Kidney renal cell Cancer",
       max(nullif(kidney_renal_cell_cancer_age,''))::numeric as "Kidney renal cell Cancer Age",
       max(nullif(multiple_kidney_renal_cell_cancers,'')) as "Multiple Kidney renal cell Cancer",
       max(nullif(leukemia,'')) as "Leukemia",
       max(nullif(leukemia_age,''))::numeric as "Leukemia Age",
       max(nullif(multiple_leukemias,'')) as "Multiple Leukemia",
       max(nullif(lung_cancer,'')) as "Lung Cancer",
       max(nullif(lung_cancer_age,''))::numeric as "Lung Cancer Age",
       max(nullif(multiple_lung_cancers,'')) as "Multiple Lung Cancer",
       max(nullif(lymphoma,'')) as "Lymphoma",
       max(nullif(lymphoma_age,''))::numeric as "Lymphoma Age",
       max(nullif(multiple_lymphomas,'')) as "Multiple Lymphoma",
       max(nullif(melanoma_skin_cancer,'')) as "Melanoma Skin Cancer",
       max(nullif(melanoma_skin_cancer_age,''))::numeric as "Melanoma Skin Cancer Age",
       max(nullif(multiple_melanoma_skin_cancers,'')) as "Multiple Melanoma Skin Cancer",
       max(nullif(nonmelanoma_skin_cancer,'')) as "Non-Melanoma Skin Cancer",
       max(nullif(nonmelanoma_skin_cancer_age,''))::numeric as "Non-Melanoma Skin Cancer Age",
       max(nullif(multiple_nonmelanoma_skin_cancers,'')) as "Multiple Non-Melanoma Skin Cancer",
       max(nullif(oral_cavity_or_throat_cancer,'')) as "Oral Cavity or Throat Cancer",
       max(nullif(oral_cavity_or_throat_cancer_age,''))::numeric as "Oral Cavity or Throat Cancer Age",
       max(nullif(multiple_oral_cavity_or_throat_cancers,'')) as "Multiple Oral Cavity or Throat Cancer",
       max(nullif(other_cancer,'')) as "Other Cancer",
       max(nullif(other_age,''))::numeric as "Other Cancer Age",
       max(nullif(multiple_other_cancers,'')) as "Multiple Other Cancer",
       max(nullif(ovarian_cancer,'')) as "Ovarian Cancer",
       max(nullif(ovarian_cancer_age,''))::numeric as "Ovarian Cancer Age",
       max(nullif(multiple_ovarian_cancers,'')) as "Multiple Ovarian Cancer",
       max(nullif(pancreatic_cancer,'')) as "Pancreatic Cancer",
       max(nullif(pancreatic_cancer_age,''))::numeric as "Pancreatic Cancer Age",
       max(nullif(multiple_pancreatic_cancers,'')) as "Multiple Pancreatic Cancer",
       max(nullif(prostate_cancer,'')) as "Prostate Cancer",
       max(nullif(prostate_cancer_age,''))::numeric as "Prostate Cancer Age",
       max(nullif(multiple_prostate_cancers,'')) as "Multiple Prostate Cancer",
       max(nullif(stomach_cancer,'')) as "Stomach Cancer",
       max(nullif(stomach_cancer_age,''))::numeric as "Stomach Cancer Age",
       max(nullif(multiple_stomach_cancers,'')) as "Multiple Stomach Cancer",
       max(nullif(testicular_cancer,'')) as "Testicular Cancer",
       max(nullif(testicular_cancer_age,''))::numeric as "Testicular Cancer Age",
       max(nullif(multiple_testicular_cancers,'')) as "Multiple Testicular Cancer",
       max(nullif(thyroid_cancer,'')) as "Thyroid Cancer",
       max(nullif(thyroid_cancer_age,''))::numeric as "Thyroid Cancer Age",
       max(nullif(multiple_thyroid_cancers,'')) as "Multiple Thyroid Cancer",
       max(nullif(unknown_cancer,'')) as "Unknown Cancer",
       max(nullif(unknown_cancer_age,''))::numeric as "Unknown Cancer Age",
       respondent_id                            as "Respondent",
       step_instance                            as "Instance",
       count(*)                                 as "Source rows"
from surveyreport.fact_sections_view
where coalesce(step,'') not in ('Welcome','Demographics','Thank you')
group by respondent_id, step, step_instance
order by respondent_id, step, step_instance
