#!/usr/bin/env bash
#
# Builds the Elicit installation manual (umbrella UC-002).
#
# The manual is typeset by a TeX Live container, so no TeX installation is needed on the
# machine doing the build (NFR-002). The platform version and build date are stamped into
# the document (UC-002 BR-002); when they are not supplied both read "unknown" (UC-002 A2,
# BR-003), so a copy is never silently undated.
#
# Unlike the author's manual, this PDF is a release artifact of the umbrella repository.
# It is not packaged into, and not served by, any module image (umbrella C-001): an
# operator reads it before there is an Elicit site to serve it from (UC-001 BR-001).
#
# Usage: docs/manual/build-manual.sh [version] [build-date]
#
# Env:
#   TEXLIVE_IMAGE   container image to typeset with (default texlive/texlive:latest)
#   MANUAL_OUT      where to write the PDF (default docs/manual)
#   SKIP_MANUAL=1   skip the build entirely and exit 0

set -euo pipefail

MANUAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${MANUAL_DIR}/../.." && pwd)"

TEXLIVE_IMAGE="${TEXLIVE_IMAGE:-texlive/texlive:latest}"
MANUAL_OUT="${MANUAL_OUT:-${MANUAL_DIR}}"
JOB="elicit-installation-manual"
PDF_NAME="${JOB}.pdf"

if [[ "${SKIP_MANUAL:-0}" == "1" ]]; then
  echo "[manual] SKIP_MANUAL=1 — not building the manual"
  exit 0
fi

# The version and build date the PDF is stamped with (UC-002 steps 2 and 3).
#
# The umbrella holds no pom.xml of its own, and its git tags version the repository rather
# than the platform — v1.1.1 while the modules are at 3.0.0 — so a tag is the wrong source.
# The platform version is what the applications carry, and they carry one version between
# them. Take it from the three modules when they agree, and stamp "unknown" otherwise rather
# than pick one: a wrong version on the title page is worse than an absent one (BR-003).
VERSION="${1:-}"
BUILD_DATE="${2:-}"
if [[ -z "${VERSION}" ]]; then
  declare -a MODULE_VERSIONS=()
  for module in Survey Admin Author; do
    pom="${REPO_DIR}/${module}/pom.xml"
    [[ -f "${pom}" ]] || continue
    v="$(sed -n '1,30p' "${pom}" | grep -m1 -o '<version>[^<]*</version>' | sed 's/<[^>]*>//g' || true)"
    [[ -n "${v}" ]] && MODULE_VERSIONS+=("${v}")
  done
  if [[ ${#MODULE_VERSIONS[@]} -eq 3 ]]; then
    UNIQUE="$(printf '%s\n' "${MODULE_VERSIONS[@]}" | sort -u | wc -l | tr -d ' ')"
    if [[ "${UNIQUE}" == "1" ]]; then
      VERSION="${MODULE_VERSIONS[0]}"
    else
      echo "[manual] Survey, Admin and Author disagree on their version" \
           "(${MODULE_VERSIONS[*]}) — stamping \"unknown\". Pass a version to override." >&2
    fi
  elif [[ ${#MODULE_VERSIONS[@]} -gt 0 ]]; then
    echo "[manual] not every module is cloned — stamping \"unknown\"." \
         "Pass a version to override." >&2
  fi
fi
VERSION="${VERSION:-unknown}"
BUILD_DATE="${BUILD_DATE:-$(date -u '+%Y-%m-%d %H:%M:%S UTC')}"

if ! command -v docker >/dev/null 2>&1; then
  echo "[manual] docker is not available — cannot typeset the manual." >&2
  echo "[manual] Install Docker, or set SKIP_MANUAL=1 to skip the manual." >&2
  exit 1
fi

echo "[manual] version ${VERSION}, built ${BUILD_DATE}"

# LaTeX takes the stamp from a generated file rather than the command line, so the same
# sources build by hand (with "unknown") and in a release (with the real values).
cat > "${MANUAL_DIR}/build-info.tex" <<EOF
%% Generated by docs/manual/build-manual.sh — do not edit, do not commit.
\\newcommand{\\elicitVersion}{${VERSION}}
\\newcommand{\\elicitBuildDate}{${BUILD_DATE}}
EOF

echo "[manual] typesetting with ${TEXLIVE_IMAGE}"
docker run --rm \
  -v "${MANUAL_DIR}:/manual" \
  -w /manual \
  -u "$(id -u):$(id -g)" \
  -e HOME=/tmp \
  "${TEXLIVE_IMAGE}" \
  latexmk -lualatex -interaction=nonstopmode -halt-on-error -file-line-error \
          -outdir=build "${JOB}.tex"

mkdir -p "${MANUAL_OUT}"
if [[ "${MANUAL_OUT}" != "${MANUAL_DIR}" ]]; then
  cp "${MANUAL_DIR}/build/${JOB}.pdf" "${MANUAL_OUT}/${PDF_NAME}"
else
  cp "${MANUAL_DIR}/build/${JOB}.pdf" "${MANUAL_DIR}/${PDF_NAME}"
fi

echo "[manual] wrote ${MANUAL_OUT}/${PDF_NAME} ($(du -h "${MANUAL_OUT}/${PDF_NAME}" | cut -f1))"
